# Generated by Django 2.1.4 on 2019-10-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajoutformationliste',
            old_name='tr_body',
            new_name='body_tr',
        ),
    ]
