# Generated by Django 2.1.4 on 2019-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191017_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajoutformationliste',
            name='body_tr',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ajoutformationliste',
            name='head',
            field=models.CharField(max_length=500),
        ),
    ]
