# Generated by Django 2.1.4 on 2019-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191017_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajoutformationliste',
            name='body_tr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ajoutformationliste',
            name='head',
            field=models.TextField(),
        ),
    ]
