# Generated by Django 2.1.4 on 2019-10-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191017_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='id',
        ),
        migrations.AddField(
            model_name='formation',
            name='id_formation',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
