# Generated by Django 2.1.4 on 2019-10-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191017_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierDetailFormation',
            fields=[
                ('id_formation', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('head', models.TextField()),
                ('body_tr', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='AjoutFormationListe',
            new_name='ModifierListeFormation',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
    ]
