# Generated by Django 2.1.4 on 2019-10-17 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191017_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id_event', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_time_event', models.DateTimeField(blank=True, null=True)),
                ('place_event', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id_news', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
    ]
