# Generated by Django 2.1.4 on 2019-10-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_events_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id_active', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('content_active', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id_citc', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('content_citc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='id_event',
        ),
        migrations.AddField(
            model_name='events',
            name='detail_event',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='id_events',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='events',
            name='resume_event',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='detail_news',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='resume_news',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
