# Generated by Django 2.1.4 on 2019-10-17 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191017_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date_pub',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
