# Generated by Django 2.1.4 on 2019-10-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191017_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='resume_event',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='resume_news',
            field=models.TextField(),
        ),
    ]
