# Generated by Django 2.1.4 on 2019-10-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191017_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierListeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
