# Generated by Django 2.1.4 on 2019-10-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_modifierlistenews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModifierListeNews',
            new_name='ModifierGrille',
        ),
    ]
