# Generated by Django 2.1.4 on 2019-10-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191017_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumb',
            field=models.CharField(default='', max_length=300),
        ),
    ]
