# Generated by Django 2.1.4 on 2019-10-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191018_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='presentation',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
