# Generated by Django 2.1.4 on 2019-10-19 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191018_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignages',
            name='date_pub',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
