# Generated by Django 2.1.4 on 2019-10-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_temoignages_date_pub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Evenements'},
        ),
        migrations.AlterModelOptions(
            name='homecontainer',
            options={'verbose_name': 'Home Container'},
        ),
        migrations.AlterModelOptions(
            name='modifierdetailformation',
            options={'verbose_name_plural': "Modifier le contenu d'une formation en particulier"},
        ),
        migrations.AlterModelOptions(
            name='modifiergrille',
            options={'verbose_name_plural': 'Modifier la grille bootstrap (de news et/ou events)'},
        ),
        migrations.AlterModelOptions(
            name='modifierlisteformation',
            options={'verbose_name_plural': 'Modifier la liste des formations du CITC'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name_plural': 'CITC'},
        ),
        migrations.AlterModelOptions(
            name='temoignages',
            options={'verbose_name': 'Liste des Temoignage'},
        ),
        migrations.AddField(
            model_name='modifiergrille',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
