# Generated by Django 2.1.4 on 2019-10-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191021_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecontainer',
            options={'verbose_name_plural': "Modification de certains 'Containers' de la page d'Accueil"},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='temoignages',
            options={'verbose_name_plural': 'Liste des Temoignages'},
        ),
        migrations.AlterField(
            model_name='modifiergrille',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
