# Generated by Django 2.1.4 on 2019-10-21 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191021_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_pub',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
