# Generated by Django 2.1.4 on 2019-10-21 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191021_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_pub',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
