# Generated by Django 2.1.4 on 2019-10-22 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191021_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
