# Generated by Django 2.1.4 on 2019-10-22 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191022_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_pub',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='id_events',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
