# Generated by Django 2.1.4 on 2019-10-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20191022_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active',
        ),
    ]
